"""Configuration for Neural Cryptanalysis Key Recovery Attack"""

DATA_SIZE = 10000
KEY_SIZE = 32
PLAINTEXT_SIZE = 16
CIPHERTEXT_SIZE = 16
SEQUENCE_LENGTH = 8
BATCH_SIZE = 32
EPOCHS = 50
LEARNING_RATE = 0.001
VALIDATION_SPLIT = 0.2
TEST_SPLIT = 0.1
RNN_UNITS = 128
LSTM_UNITS = 256
BILSTM_UNITS = 256
GRU_UNITS = 128
DROPOUT_RATE = 0.3
FC_LAYERS = [512, 256, 128, 64]
FC_ACTIVATION = 'relu'
USE_LSTM = True
USE_BILSTM = True
USE_RNN = True
USE_GRU = True
USE_FC = True
DATA_DIR = './data'
MODEL_DIR = './models'
RESULTS_DIR = './results'